[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 8080

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
